name: Build on master push (amd64 only)
# see https://iam.thunder.spb.ru/posts/2021/01/09/github-actions-and-pushing-container-to-multiple-registries
# 
# https://linuxtut.com/en/b0291c1bc1141a535263/

on:
  push:
    branches:
      - master

env:
  DOCKER_CLI_EXPERIMENTAL: enabled

jobs:
  build:
    name: Build electrs image
    runs-on: ubuntu-18.04
    env:
      VERSION: v0.9.4
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/build-push-action@v2
        with: 
          registry: ghcr.io 
          username: ${{ github.repository_owner }} 
          password: ${{ secrets.GITHUB_TOKEN }}
          secrets: |
            GITHUB_TOKEN=${{ github.token }}

      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        id: qemu

      - name: Setup Docker buildx action
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Show available Docker buildx platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
#      - name: Run Docker buildx
#        run: |
#          docker buildx build \
#          --platform linux/amd64 \
#          --build-arg VERSION=$VERSION \
#          --tag ghcr.io/${{ github.actor }}/electrs:$VERSION \
#          --output "type=registry" .
